// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqD3QhvCbizx0w4C5xJuNWc8iKmTUF0kk',
    appId: '1:793980032932:web:06582cc82c88ac67fd1331',
    messagingSenderId: '793980032932',
    projectId: 'alarm-demo-af881',
    authDomain: 'alarm-demo-af881.firebaseapp.com',
    storageBucket: 'alarm-demo-af881.firebasestorage.app',
    measurementId: 'G-VN0KM6NYGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Q0wLHk-QrjCLP7zjwUnPGrszU6k1LmI',
    appId: '1:793980032932:android:96bffa02bd11b94dfd1331',
    messagingSenderId: '793980032932',
    projectId: 'alarm-demo-af881',
    storageBucket: 'alarm-demo-af881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1krfGupz19L9BWcPMiM1ov2wq7b0Yrr4',
    appId: '1:793980032932:ios:d436e79ce8e79987fd1331',
    messagingSenderId: '793980032932',
    projectId: 'alarm-demo-af881',
    storageBucket: 'alarm-demo-af881.firebasestorage.app',
    iosBundleId: 'com.example.alarmDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1krfGupz19L9BWcPMiM1ov2wq7b0Yrr4',
    appId: '1:793980032932:ios:d436e79ce8e79987fd1331',
    messagingSenderId: '793980032932',
    projectId: 'alarm-demo-af881',
    storageBucket: 'alarm-demo-af881.firebasestorage.app',
    iosBundleId: 'com.example.alarmDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqD3QhvCbizx0w4C5xJuNWc8iKmTUF0kk',
    appId: '1:793980032932:web:216ce4728b60082bfd1331',
    messagingSenderId: '793980032932',
    projectId: 'alarm-demo-af881',
    authDomain: 'alarm-demo-af881.firebaseapp.com',
    storageBucket: 'alarm-demo-af881.firebasestorage.app',
    measurementId: 'G-V48E1EW76F',
  );
}
